/* Bank VQA module: 01-state.js */
var state = {
  target: "苏州农商行",
  peers: ["常熟农商行", "瑞丰农商行", "上海农商行", "苏州"],
  year: 2025,
  types: ["国有大行", "股份行", "城市商业银行", "农村商业银行"],
  confirmed: false,
  includedCharts: {},
  projectName: "",
  reportVersion: "董事会完整汇报版",
  peerTemplate: "manual",
  targetTypeFilter: "农商行",
  targetRegionFilter: "全部",
  targetSearch: "",
  dataTheme: "盈利质量",
  dataMetric: "roa",
  dataStep: "type",
  activeTopic: "profit",
  currentProjectId: null,
  editedNarratives: {},
  includedTopics: {},
  editedChartStories: {},
  sessionLog: [],
  watchMetrics: [],
  reportStructure: [],
  customReportPages: []
};

var data = window.VQA_DATA || { banks: [], records: [], aliases: {} };
var records = data.records || [];
var banks = data.banks || [];
var analysisRules = null;
var metricDictionary = {};
var fieldCoverageMatrix = [];
var languageDiscipline = null;

var metricLabel = {
  roa: "总资产收益率",
  roe: "净资产收益率",
  coreRevenueGrowth: "核心营收增速",
  nim: "净息差",
  nimGapBp: "息差对冲缺口",
  nimGapPointComputed: "息差对冲缺口",
  earningAssetYieldChange: "生息资产收益率变化",
  interestLiabilityCostChange: "计息负债成本率变化",
  nimGapPoint: "NIM缺口",
  realLoanDepositSpread: "真实存贷利差",
  feeAssetRatio: "手续费资产比",
  netInterestRevenueShare: "利息净收入占比",
  feeRevenueShare: "手续费收入占比",
  coreRevenueShare: "核心营收占比",
  trueCoreNonInterest: "真实核心非息占比",
  volatileIncomeShare: "高波动收入占比",
  pb: "年末市净率",
  pbMid: "年中市净率",
  theoreticalPb: "DDM理论PB",
  pbDiscount: "PB估值偏离",
  economicProfit: "经济利润",
  basicEps: "基本每股收益",
  ppopGrowth: "拨备前利润增速",
  revenueGrowth: "营业收入增速",
  profitPpopGap: "净利与拨备前利润增速缺口",
  provisionCoverageChange: "拨备覆盖率变化",
  overdueNplDeviation: "逾期不良偏离度",
  hiddenNplExposure: "隐性不良暴露率",
  provisionCoverage: "拨备覆盖率",
  assetGrowth: "总资产增速",
  loanAssetRatio: "贷款/资产",
  depositLiabilityRatio: "存款/负债",
  cet1Change: "核心一级资本充足率变化",
  carBuffer: "资本充足率余量",
  estimatedRwa: "估算风险加权资产",
  estimatedRwaGrowth: "估算风险加权资产增速",
  rwaProfitGrowthGap: "RWA增速-净利润增速缺口",
  rwaAssetGrowthGap: "RWA增速-资产增速缺口",
  costIncomeRatio: "成本收入比",
  npl: "不良率",
  corporateLoanNpl: "公司贷款不良率",
  personalLoanNpl: "个贷不良率",
  billDiscountNpl: "票据贴现不良率",
  housingLoanShare: "住房贷款占比",
  consumerLoanShare: "消费贷款占比",
  businessLoanShare: "经营贷款占比",
  housingLoanNpl: "住房贷款不良率",
  consumerLoanNpl: "消费贷款不良率",
  businessLoanNpl: "经营贷款不良率",
  retailRiskMax: "零售最高分项不良率",
  retailRiskSpread: "零售分项风险分化",
  timeDepositShare: "定期存款占比",
  corporateDepositShare: "公司存款占比",
  personalDepositShare: "个人存款占比",
  corporateDemandDepositShare: "公司活期存款占比",
  personalDemandDepositShare: "个人活期存款占比",
  earningAssetYield: "生息资产收益率",
  interestLiabilityCost: "计息负债成本率",
  cet1Buffer: "核心一级资本余量",
  rwaDensity: "风险加权资产密度",
  liquidityRatio: "流动性比率",
  liquidityCoverageRatio: "流动性覆盖率",
  investmentAssetRatio: "债券基金信托理财/资产",
  bondAssetRatio: "债券投资/资产",
  fundAssetRatio: "基金投资/资产",
  trustWmAssetRatio: "信托及理财/资产",
  bondInvestment: "债券投资",
  fundInvestment: "基金投资",
  trustWmInvestment: "信托及理财投资",
  adminExpense: "管理费用",
  adminAssetRatio: "管理费用/资产",
  cashProfitRatio: "经营现金流/净利润",
  operatingCashFlow: "经营活动现金流净额",
  assets: "总资产",
  assetsChange: "总资产变化",
  liabilities: "总负债",
  equity: "股东权益",
  loans: "发放贷款和垫款",
  deposits: "吸收存款",
  revenue: "营业收入",
  coreRevenue: "核心营收",
  netProfit: "净利润",
  netProfitGrowth: "净利润增速",
  ppop: "拨备前利润",
  netInterestIncome: "利息净收入",
  nonInterestShare: "非息收入占比",
  feeIncome: "手续费及佣金净收入",
  interestIncome: "利息收入",
  interestExpense: "利息支出",
  incomeTax: "所得税费用",
  overdueRatio: "逾期贷款率",
  specialMentionRatio: "关注类贷款占比",
  cet1: "核心一级资本充足率",
  corporateDeposit: "公司存款",
  personalDeposit: "个人存款",
  corporateDemandDeposit: "公司活期存款",
  personalDemandDeposit: "个人活期存款",
  corporateTimeDeposit: "公司定期存款",
  personalTimeDeposit: "个人定期存款",
  demandDepositShare: "活期存款占比",
  earningAssets: "生息资产",
  earningAssetsSource: "生息资产数据来源",
  earningAssetYieldSource: "生息资产收益率数据来源",
  interestLiabilities: "计息负债",
  interestLiabilityCostSource: "计息负债成本率数据来源",
  nimGapSource: "息差对冲缺口计算口径",
  operatingCashFlowChange: "经营现金流变化",
  operatingCashFlowGrowth: "经营现金流增速",
  estimatedRwaChange: "估算风险加权资产变化",
  pbChange: "市净率变化"
};
